[package]
name = "ck_lightning_client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
ic-lightning-relay = { path = "../ic-lightning-relay" }
cklightning = { path = "../ckLightning-canister" }
candid = "=0.10.19"
anyhow = "1.0.100"
serde = "=1.0.219"
ic-agent = { version = "0.39.3", features = ["wasm-bindgen"] }
clap = { version = "4.5", features = ["derive"] }
ic-ledger-types = "0.15.0"
icrc-ledger-types = "0.1.10"
log = "0.4.29"
env_logger = "0.11.8"
bitcoin = { version = "0.32", features = ["rand"] }
lightning-invoice = "0.33.0"
hex = "0.4.3"

[profile.release]
overflow-checks = true


